#!/bin/sh

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(yay -Qum 2> /dev/null | wc -l); then
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

sed -i '2s/.*/echo "📦 $updates"/' ~/Docs/Scripts/blocks/s-packages

#if [ "$updates" -gt 0 ]; then
#   sed -i '2s/.*/echo "📦 $updates"/' ~/Docs/Scripts/blocks/s-packages
#else
#   sed -i '2s/.*/echo "📦 0"/' ~/Docs/Scripts/blocks/s-packages
#fi

pkill -SIGRTMIN+3 i3blocks
#pkill -RTMIN+4 dwmblocks
