#!/bin/sh

user=$(id -u)
group=$(id -g)

mountable=$(lsblk -lp | grep -v nvme0n1p1 | grep -v sda | grep "part $" | awk '{print $1, "(" $4 ")"}')
[[ "$mountable" = "" ]] && notify-send -u normal "No mountable drivers available" && exit 1

#chosen=$(echo "$mountable" | rofi -dmenu -i -p "Mount which drive?" | awk '{print $1}')
chosen=$(echo "$mountable" |  dmenu -p "Mount which drive?" | awk '{print $1}')
[[ "$chosen" = "" ]] && exit 1

available_dirs=$(find /media -type d -maxdepth 1 2>/dev/null)
#mountpoint=$(echo "$available_dirs" | rofi -dmenu -i -p "Select mount point")
mountpoint=$(echo "$available_dirs" | dmenu -p "Select mount point")
[[ "$mountpoint" = "" ]] && exit 1

if [[ ! -d "$mountpoint" ]]; then
    #mkdiryn=$(echo -e "Yes\nNo" | rofi -dmenu -i -p "$mountpoint does not exist. Create it?")
    mkdiryn=$(echo -e "Yes\nNo" | dmenu -p "$mountpoint does not exist. Create it?")
    [[ "$mkdiryn" = Yes ]] && sudo mkdir -p "$mountpoint" && sudo mount -o rw,uid=$user,gid=$group $chosen $mountpoint && pgrep -x dunst && notify-send -u normal "$chosen" "Mounted on $mountpoint." || exit 1
else
    sudo mount -o rw,uid=$user,gid=$group $chosen $mountpoint && pgrep -x dunst && notify-send -u normal "$chosen" "Mounted on $mountpoint."
fi
