#!/bin/sh
bluetoothctl | while read -r; do
    if [ "$(bluetoothctl show | grep Powered | cut -d ' ' -f 2)" = "yes" ]; then
        echo ""

        devices_paired=$(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2)
        counter=0

        echo "$devices_paired" | while read -r line; do
            device_info=$(bluetoothctl info "$line")

            if echo "$device_info" | grep -q "Connected: yes"; then
                device_alias=$(echo "$device_info" | grep "Alias" | cut -d ' ' -f 2-)
                echo ""
                counter=$((counter + 1))
            fi
        done
    else
        echo ""
    fi
done
