#!/bin/sh

ufw_active=$(sudo ufw status verbose | grep Status | cut -d ' ' -f2)
ufw_active_home=$(sudo ufw status verbose | grep To)

check_ufw(){
    if [ $ufw_active = "inactive" ]; then
        echo "Inactive"
    elif [ "$ufw_active_home" ]; then
        echo "Home"
    else
        echo "Public"
    fi
}

ufw_toggle(){
    if [ "$ufw_active" = "inactive" ]; then
            sudo ufw enable && sleep 5
    fi

    if [ "$ufw_active_home" ]; then
        echo yes | sudo ufw delete 1
        notify-send -u normal -t 1500 "UFW" "Public Profile Set" --icon="~/.config/dunst/icons/firewall.png"
        echo " Public"
    else
        sudo ufw allow from 192.168.1.253 to any port 22000 comment 'syncthing pi'
        notify-send -u normal -t 1500 "UFW" "Home Profile Set" --icon="~/.config/dunst/icons/firewall.png"
        echo " Home"
    fi
}

case "$1" in
    --toggle)
        ufw_toggle
        ;;
    *)
        check_ufw
        ;;
esac
